Fix error in package-lock.json
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js:115:9)
    at Object.<anonymous> (/home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js:124:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at cjsLoader (node:internal/modules/esm/translators:298:15)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:240:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
      at Module._load (node:internal/modules/cjs/loader:1038:27)
      at Module.require (node:internal/modules/cjs/loader:1289:19)
      at require (node:internal/modules/helpers:182:18)
      at requireWithFriendlyError (/home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js:97:10)
      at Object.<anonymous> (/home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js:124:76)
      at Module._compile (node:internal/modules/cjs/loader:1521:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
      at Module.load (node:internal/modules/cjs/loader:1266:32)
      at Module._load (node:internal/modules/cjs/loader:1091:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/runner/work/raid-au/raid-au/raid-agency-app/node_modules/rollup/dist/native.js'
    ]
  }
}